### ISSUE TITLE
get_raster_eigen_treelocs step 9 Error within extract

### ISSUE THREAD

**Issue by cingularities** [bi0m3trics/spanner#7]
Hello, I am getting an error for step 9, am I missing something?

Best,
Cindy

 las_check(UAV_MtB_normalized_height)

 Checking the data
  - Checking coordinates... ✓
  - Checking coordinates type... ✓
  - Checking coordinates range... ✓
  - Checking coordinates quantization... ✓
  - Checking attributes type... ✓
  - Checking ReturnNumber validity... ✓
  - Checking NumberOfReturns validity... ✓
  - Checking ReturnNumber vs. NumberOfReturns... ✓
  - Checking RGB validity... ✓
  - Checking absence of NAs... ✓
  - Checking duplicated points...
    ⚠ 66523 points are duplicated and share XYZ coordinates with other points
  - Checking degenerated ground points...
    ⚠ There were 22420 degenerated ground points. Some X Y Z coordinates were repeated
    ⚠ There were 1317790 degenerated ground points. Some X Y coordinates were repeated but with different Z coordinates
  - Checking attribute population...
    🛈 'PointSourceID' attribute is not populated
    🛈 'ScanDirectionFlag' attribute is not populated
    🛈 'EdgeOfFlightline' attribute is not populated
  - Checking gpstime incoherances
    ✗ 760900 pulses (points with the same gpstime) have points with identical ReturnNumber
  - Checking flag attributes... ✓
  - Checking user data attribute... ✓
 Checking the header
  - Checking header completeness... ✓
  - Checking scale factor validity... ✓
  - Checking point data format ID validity... ✓
  - Checking extra bytes attributes validity... ✓
  - Checking the bounding box validity... ✓
  - Checking coordinate reference system... ✓
 Checking header vs data adequacy
  - Checking attributes vs. point format...
    ✗ Invalid file: the data contains a 'gpstime' attribute but point data format is not set to 1, 3, 6, 7 or 8.
  - Checking header bbox vs. actual content... ✓
  - Checking header number of points vs. actual content... ✓
  - Checking header return number vs. actual content... ✓
 Checking coordinate reference system...
  - Checking if the CRS was understood by R... ✓
 Checking preprocessing already done 
  - Checking ground classification... yes
  - Checking normalization... maybe
  - Checking negative outliers...
    ⚠ 448433 points below 0
  - Checking flightline classification... no
 Checking compression
  - Checking attribute compression...
   -  ScanDirectionFlag is compressed
   -  EdgeOfFlightline is compressed
   -  Synthetic_flag is compressed
   -  Keypoint_flag is compressed
   -  Withheld_flag is compressed
   -  UserData is compressed
   -  PointSourceID is compressed
> #SPANNER
> UAV_MtB_myTreeLocs = spanner::get_raster_eigen_treelocs(las = UAV_MtB_normalized_height, res = 0.05, 
+                                                     pt_spacing = 0.0254, 
+                                                     dens_threshold = 0.2, 
+                                                     neigh_sizes=c(0.333, 0.166, 0.5), 
+                                                     eigen_threshold = 0.5, 
+                                                     grid_slice_min = 0.6666, 
+                                                     grid_slice_max = 2.0,
+                                                     minimum_polygon_area = 0.025, 
+                                                     cylinder_fit_type = "ransac", 
+                                                     output_location = "//snow/projects/Babst_Lidar_treering_CLN/CLNorton/TLiDAR/outputs", 
+                                                     max_dia=0.5, 
+                                                     SDvert = 0.25)
Downsampling the scan... (step 1 of 14)

Creating processing slice... (2/14)

Calculating verticality... (3/14)

Creating canopy cover raster... (4/14)

Calculating relative density... (5/14)

Gridding relative density... (6/14)

Gridding verticality... (7/14)

Merging relative density and verticality... (8/14)

Filtering merged polygon... (9/14)

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'y' in selecting a method for function 'extract': error in evaluating the argument 'x' in selecting a method for function 'vect': error in evaluating the argument 'x' in selecting a method for function 'addAttrToGeom': subscript out of bounds
In addition: Warning message:
attribute variables are assumed to be spatially constant throughout all geometries

**Comment by bi0m3trics** [comment]
It's going to be hard to advise/diagnose without a reproducible example or a .laz file. Do you have something you could share? I can clearly see that the error is originating from one of the five calls to terra:extract in lines 155-171 of get_raster_eigen_treelocs, where it uses the density and verticality grids to find probable tree locations, but it's impossible to figure out why without a data example.

**Comment by cingularities** [comment]
Hello,
Thank you for the response. oh yes, please link [https://arizona.box.com/s/gm2twtyv8jk6xe7vrjn6n8xw59du9i03](url)

**Comment by bi0m3trics** [comment]
@cingularities Nope. can't access...
![image](https://github.com/bi0m3trics/spanner/assets/3956719/a52813f8-a43d-4cce-8d32-d1e761f1a5da)

**Comment by cingularities** [comment]
Please retry the link, I edited permissions. Thank you!

**Comment by bi0m3trics** [comment]
@cingularities have a look at [7b3f947](https://github.com/bi0m3trics/spanner/commit/7b3f9470fbfe2903c77f4cf949b320159ec31d5f) and then try reducing the minimum_polygon_area threshold to get it to run. I had to reduce yours to 0.001 to get the script to run. 

FYI - I don't recommend using spanner for your UAS SfM data as you will likely never have adequate point density sub-canopy for the ransac cylinder fitting to work properly, and suggest using algo's that focus on top down segmentation (e.g., https://r-lidar.github.io/lidRbook/itd-its.html). 

Anyhow - thank you for submitting the issue, and I added quite a few, more informative, error messages to help future suers when encountering issues.

**Comment by cingularities** [comment]
Thank you for the pointers and information. I was testing UAS LiDAR on spanner but I will stick to using it on our TLS instead. Additionally, thank you for the wonderful package and updates! Are there any developments in segmenting branches after main stem?

**Comment by bi0m3trics** [comment]
@cingularities We just got our Riegl 600i last week so anything's possible. What I've been working on lately (aside from troubleshooting the patchmorph code in my other repository) is replacing the cylinderfit code from TreeLS (since Tiago hasn't worked on that package in years) and seeing if I can make the igraph code faster. I'm also working on some coarse woody debris segmentation stuff...
Any chance you work with [tyson-swetnam](https://github.com/tyson-swetnam)? If you make it up the hill, feel free to stop by!
