### ISSUE TITLE
Units of measurement in ft

### ISSUE THREAD

**Issue by summitbri** [bi0m3trics/spanner#8]
Hello.  More of a dumb question vs an issue.  Should this work on a point cloud with xyz units all in feet (sft) provided that i adjust the recommended parameters to values in feet?  Or do I need my source point cloud to be in meters to be successful with the algorithms?  Thank you!

**Comment by bi0m3trics** [comment]
@summitbri  - I honestly have no idea. There's nothing internal that that's fixed to units, so I say give it a whirl and let me know.  Bonus points for pics!
-a
